-- Migration: 20260920000034_phase7a_patients_and_admissions | Purpose: the patient
-- identity the details step collects and the admission an IPD bill posts its credit to.
-- Target: PostgreSQL 17 (Supabase)
-- Idempotent: if-not-exists tables/columns/indexes, drop-policy-if-exists before every
-- policy, create-or-replace functions, guarded constraints and grants.
--
-- What this file decides, because D-067 left it open
-- -------------------------------------------------
-- D-067 recorded the open question in its own words: "A counter patient is not
-- necessarily a customer row, so Phase 7 decides whether a counter sale finds-or-
-- creates a customer, or stays denormalised on the sale." **This file answers it: the
-- patient IS a `customers` row.** The owner's brief says so - "Use the existing
-- customers identity where compatible; do not create a competing patient master
-- without demonstrating why it is necessary" - and nothing here demonstrates a reason
-- for a second identity table. So `customers` gains the fields a patient needs (a
-- generated code, the demographics the details step asks for) and the sale keeps its
-- own `patient_name` / `patient_mobile` snapshot (D-067) so that editing a patient
-- later cannot rewrite an old bill.
--
-- Admission is a different thing from patient, and the brief says why: one patient
-- has many admissions over time. `admissions` is therefore its own table, linked to
-- the patient (`customer_id`) and to the hospital, and it carries the hospital's own
-- IPD number. That number is D-067's `hospital_reference`: the *external* reference.
-- It is not the patient's id and it is not a UUID - D-067 already resolved that
-- ("It is one column - hospital_reference, the OPD/IPD number - and patient_id is not
-- a column"), and this file keeps the two identities apart: `customers.id` /
-- `customers.patient_code` name the patient, `admissions.admission_no` names the
-- episode at the hospital.
--
-- The money is NOT computed here. This file creates the identity and the episode; the
-- charges, returns, allocations and balances that make an admission's outstanding a
-- server-derived figure live in 00035, next to the sale write path that creates them.

-- ---------------------------------------------------------------------------
-- 1. customers - the patient fields, additive and all nullable
--
--    Every column is nullable on purpose. Existing customers are suppliers' accounts
--    and walk-ins with no patient identity, and the phase's own rule is that existing
--    rows are not silently converted (the brief: "Do not silently convert existing
--    rows or historical transactions"). A NULL `patient_code` therefore means
--    "registered before Phase 7a and not yet used as a patient", which is exactly what
--    it is - it is not "patient number zero".
--
--    `patient_code` is generated by `next_patient_code()` below, never by a client, and
--    unique per pharmacy. `phone` stays what it always was - the contact - and the
--    unique key is on the code, never on the phone: families share a mobile number
--    (the brief: "Do not use mobile number as patient ID or enforce phone uniqueness").
-- ---------------------------------------------------------------------------
alter table public.customers
  add column if not exists patient_code    text,
  add column if not exists date_of_birth   date,
  add column if not exists age_years       int,
  add column if not exists age_months      int,
  add column if not exists sex             text,
  add column if not exists guardian_name   text,
  add column if not exists guardian_phone  text,
  add column if not exists notes           text;

comment on column public.customers.patient_code is
  'Human-readable patient number, unique per pharmacy, generated server-side by next_patient_code(). NULL means the row predates Phase 7a and has not yet been used as a patient; it is assigned on first use. Never a client-supplied value.';
comment on column public.customers.date_of_birth is
  'Optional. Age in years/months is recorded instead when that is what the patient gave (the details step accepts either).';
comment on column public.customers.age_years is
  'Optional age in years, the unit the brief requires. Kept beside age_months rather than folded into a single integer so "18 months" stays a correct answer.';
comment on column public.customers.sex is
  'Optional: male, female or other. Stored as text with a CHECK rather than an enum because it is descriptive, not a classification anything branches on.';
comment on column public.customers.guardian_phone is
  'A guardian''s mobile, which satisfies the contact requirement for a child or dependant. Canonicalised the same way a patient''s own number is.';
comment on column public.customers.phone is
  'The patient''s contact number in canonical 10-digit form when one was given; otherwise the guardian''s, so a family is still findable by the number they gave. Canonicalisation happens on write (save_patient), never as a bulk rewrite of existing rows.';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'customers_sex_check'
  ) then
    alter table public.customers
      add constraint customers_sex_check
      check (sex is null or sex in ('male', 'female', 'other'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'customers_age_check'
  ) then
    alter table public.customers
      add constraint customers_age_check
      check (
        (age_years is null or (age_years >= 0 and age_years <= 150))
        and (age_months is null or (age_months >= 0 and age_months <= 11))
      );
  end if;
end $$;

-- The patient code is unique within the tenant. NULLs are distinct in a Postgres
-- unique index, so every pre-Phase-7a row coexists with every other and with new rows
-- until each is given a code.
create unique index if not exists customers_pharmacy_patient_code_key
  on public.customers (pharmacy_id, patient_code);

-- Not unique: a shared family mobile is a legitimate pair of rows (the brief: "Shared
-- mobile numbers remain separate patients").
create index if not exists customers_pharmacy_phone_idx
  on public.customers (pharmacy_id, phone);

-- ---------------------------------------------------------------------------
-- 2. patient_counters + next_patient_code() - the code is allocated atomically
--
--    The same shape as `invoice_counters` / `next_sale_invoice_no()` (migration
--    00019): one row per tenant, bumped inside the inserting transaction, so two
--    counter staff registering a patient at the same moment cannot be handed the same
--    number. Written only by the function - like invoice_counters, this table has RLS
--    enabled and no policy at all, so no client can mint a code.
-- ---------------------------------------------------------------------------
create table if not exists public.patient_counters (
  pharmacy_id uuid primary key references public.pharmacies(id) on delete cascade,
  next_no int not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.patient_counters is
  'Per-pharmacy patient-code sequence. Read and bumped only by next_patient_code(); no client policy exists, so a code cannot be minted or reused from outside a SECURITY DEFINER call.';

alter table public.patient_counters enable row level security;

create or replace function public.next_patient_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pharmacy uuid := public.get_my_pharmacy_id();
  v_no int;
begin
  if v_pharmacy is null then
    raise exception 'no pharmacy scope for the signed-in user'
      using errcode = 'insufficient_privilege';
  end if;

  insert into public.patient_counters (pharmacy_id, next_no)
  values (v_pharmacy, 2)
  on conflict (pharmacy_id)
    do update set next_no = public.patient_counters.next_no + 1,
                  updated_at = now()
  returning next_no - 1 into v_no;

  -- PT-00001. Short enough to read off a card, wide enough for a pharmacy that
  -- registers a hundred thousand patients.
  return 'PT-' || lpad(v_no::text, 5, '0');
end;
$$;

comment on function public.next_patient_code() is
  'The next patient code for the caller''s pharmacy, e.g. PT-00042. Atomic under concurrent registrations and scoped to the caller, never to an argument.';

-- ---------------------------------------------------------------------------
-- 3. normalize_indian_mobile() - one canonical form for every mobile we store or match
--
--    The brief: "Normalize Indian mobile input consistently; accept +91 formatting and
--    store canonical form." Returns NULL for anything that is not a 10-digit Indian
--    mobile (starting 6-9) rather than raising, because it is used in two places with
--    two different needs: a write path that must refuse a bad number with its own
--    wording, and a search path where a nonsense term simply matches no phone. A
--    landline is deliberately not accepted as a mobile - the details step requires a
--    mobile, and silently storing "011-2345" as one would make the lookup useless.
-- ---------------------------------------------------------------------------
create or replace function public.normalize_indian_mobile(p_text text)
returns text
language sql
immutable
set search_path = public
as $$
  select case
    when p_text is null then null
    else (
      with digits as (
        select regexp_replace(p_text, '[^0-9]', '', 'g') as d
      ), trimmed as (
        select case
          when length(d) = 12 and left(d, 2) = '91' then right(d, 10)
          when length(d) = 11 and left(d, 1) = '0'  then right(d, 10)
          else d
        end as d
        from digits
      )
      select case
        when length(d) = 10 and left(d, 1) ~ '[6-9]' then d
        else null
      end
      from trimmed
    )
  end;
$$;

comment on function public.normalize_indian_mobile(text) is
  'Canonical 10-digit Indian mobile (strips +91, spaces, dashes and a leading zero; 6-9 leading digit), or NULL when the text is not a mobile number.';

-- ---------------------------------------------------------------------------
-- 4. admissions - one episode of care, and the hospital's own number for it
--
--    `admission_no` is the hospital's IPD/OPD number - D-067's `hospital_reference`.
--    Unique per pharmacy, and that is a deliberate assumption worth stating: one number
--    names one episode. A hospital that reuses a number for a later admission of the
--    same patient is re-opening the same episode as far as this schema is concerned,
--   which is why `save_admission()` returns the existing row instead of failing.
--
--    `hospital_id` is nullable because a pharmacy may not have configured its hospital
--    yet (Phase 7a lands before the mapping is seeded); `admission_no`, `customer_id`
--    and `admitted_on` are not, because an admission without them is not an episode.
--    `treating_doctor_name` is the snapshot beside the optional `treating_doctor_id`,
--    for the same reason the sale carries `doctor_name` (D-072).
-- ---------------------------------------------------------------------------
create table if not exists public.admissions (
  id uuid primary key default gen_random_uuid(),
  pharmacy_id uuid not null references public.pharmacies(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete restrict,
  hospital_id uuid references public.hospitals(id) on delete set null,
  admission_no text not null,
  admitted_on date not null default current_date,
  discharged_on date,
  ward text,
  bed text,
  treating_doctor_id uuid references public.doctors(id) on delete set null,
  treating_doctor_name text,
  status text not null default 'active',
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admissions_pharmacy_admission_no_key unique (pharmacy_id, admission_no),
  constraint admissions_status_check check (status in ('active', 'discharged')),
  constraint admissions_discharge_check check (
    discharged_on is null or discharged_on >= admitted_on
  )
);

comment on table public.admissions is
  'One hospital episode for one patient: the IPD credit account an ipd_admission sale posts to (D-067). A patient has many over time; each has its own balance, and they are never mixed.';
comment on column public.admissions.admission_no is
  'The hospital''s own IPD/OPD number - D-067''s hospital_reference, the external identity of the episode. Unique per pharmacy. It is not the patient id and not a UUID.';
comment on column public.admissions.hospital_id is
  'The hospital, snapshotted at admission time. NULL when the pharmacy has not configured one yet.';
comment on column public.admissions.status is
  'active while the patient is in; discharged when the account is closed to new charges. Only an active admission can be selected for a new IPD bill.';
comment on column public.admissions.treating_doctor_name is
  'The treating doctor as recorded on this episode, beside the optional master link (D-072: the name is what a bill printed).';

create index if not exists admissions_pharmacy_id_idx       on public.admissions (pharmacy_id);
create index if not exists admissions_customer_id_idx       on public.admissions (customer_id);
create index if not exists admissions_pharmacy_status_idx   on public.admissions (pharmacy_id, status);
create index if not exists admissions_doctor_id_idx         on public.admissions (treating_doctor_id);

drop trigger if exists set_updated_at on public.admissions;
create trigger set_updated_at before update on public.admissions
  for each row execute function public.set_updated_at();

alter table public.admissions enable row level security;

drop policy if exists admissions_pharmacy_select on public.admissions;
create policy admissions_pharmacy_select on public.admissions
  for select using (pharmacy_id = public.get_my_pharmacy_id());

drop policy if exists admissions_pharmacy_insert on public.admissions;
create policy admissions_pharmacy_insert on public.admissions
  for insert with check (pharmacy_id = public.get_my_pharmacy_id());

drop policy if exists admissions_pharmacy_update on public.admissions;
create policy admissions_pharmacy_update on public.admissions
  for update using (pharmacy_id = public.get_my_pharmacy_id())
  with check (pharmacy_id = public.get_my_pharmacy_id());

drop policy if exists admissions_pharmacy_delete on public.admissions;
create policy admissions_pharmacy_delete on public.admissions
  for delete using (pharmacy_id = public.get_my_pharmacy_id());

-- ---------------------------------------------------------------------------
-- 5. save_admission() - find-or-create, so a returning IPD patient is one episode
--
--    The IPD details step has an admission number and, on a new admission, the date,
--    ward, bed and treating doctor. Rather than making the screen check-then-insert
--    (which races with itself on a double-submit), this does both in one transaction:
--    the number already names an episode for this patient, so it returns that row;
--    otherwise it creates one.
--
--    It fills a descriptive field only where the stored row has none. That is a
--    deliberate exception to "do not edit an existing record" and it is bounded: an
--    admission number that arrives with a ward this episode did not have is new
--    information about the same episode, and dropping it would lose what the operator
--    typed. Nothing about money, the patient, or the doctor link is ever rewritten.
-- ---------------------------------------------------------------------------
create or replace function public.save_admission(
  p_customer_id uuid,
  p_admission_no text,
  p_hospital_id uuid default null,
  p_admitted_on date default null,
  p_ward text default null,
  p_bed text default null,
  p_doctor_id uuid default null,
  p_doctor_name text default null,
  p_notes text default null
) returns public.admissions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pharmacy   uuid := public.get_my_pharmacy_id();
  v_no         text := btrim(coalesce(p_admission_no, ''));
  v_hospital   uuid := p_hospital_id;
  v_doctor     uuid := p_doctor_id;
  v_doctor_nm  text := nullif(btrim(coalesce(p_doctor_name, '')), '');
  v_admission  public.admissions;
begin
  if v_pharmacy is null then
    raise exception 'no pharmacy scope for the signed-in user'
      using errcode = 'insufficient_privilege';
  end if;

  if v_no = '' then
    raise exception 'an admission needs the hospital''s IPD or OPD number'
      using errcode = 'check_violation';
  end if;

  if not exists (
    select 1 from public.customers c
     where c.id = p_customer_id and c.pharmacy_id = v_pharmacy
  ) then
    raise exception 'that patient is not in this pharmacy'
      using errcode = 'check_violation';
  end if;

  -- No hospital given: take the pharmacy's own, which is the prefill D-067 asks for.
  if v_hospital is null then
    select p.hospital_id into v_hospital
      from public.pharmacies p
     where p.id = v_pharmacy;
  end if;

  if v_hospital is not null and not exists (
    select 1 from public.hospitals h
     where h.id = v_hospital and h.pharmacy_id = v_pharmacy
  ) then
    raise exception 'that hospital is not in this pharmacy'
      using errcode = 'check_violation';
  end if;

  if v_doctor is not null then
    select d.name into v_doctor_nm
      from public.doctors d
     where d.id = v_doctor and d.pharmacy_id = v_pharmacy;

    if not found then
      raise exception 'that doctor is not in this pharmacy'
        using errcode = 'check_violation';
    end if;
  elsif v_doctor_nm is not null then
    -- A name with no master row: match it case-insensitively, and create the master
    -- only when nothing matches, so a repeated prescriber converges on one row (D-072).
    select d.id into v_doctor
      from public.doctors d
     where d.pharmacy_id = v_pharmacy
       and lower(d.name) = lower(v_doctor_nm);

    if v_doctor is null then
      insert into public.doctors (pharmacy_id, name)
      values (v_pharmacy, v_doctor_nm)
      returning id into v_doctor;
    end if;
  end if;

  select * into v_admission
    from public.admissions a
   where a.pharmacy_id = v_pharmacy
     and a.customer_id = p_customer_id
     and a.admission_no = v_no;

  if found then
    update public.admissions a
       set ward                 = coalesce(a.ward, nullif(btrim(coalesce(p_ward, '')), '')),
           bed                  = coalesce(a.bed, nullif(btrim(coalesce(p_bed, '')), '')),
           hospital_id          = coalesce(a.hospital_id, v_hospital),
           treating_doctor_id   = coalesce(a.treating_doctor_id, v_doctor),
           treating_doctor_name = coalesce(a.treating_doctor_name, v_doctor_nm),
           notes                = coalesce(a.notes, nullif(btrim(coalesce(p_notes, '')), ''))
     where a.id = v_admission.id
    returning * into v_admission;

    return v_admission;
  end if;

  insert into public.admissions (
    pharmacy_id, customer_id, hospital_id, admission_no, admitted_on,
    ward, bed, treating_doctor_id, treating_doctor_name, notes, status
  ) values (
    v_pharmacy,
    p_customer_id,
    v_hospital,
    v_no,
    coalesce(p_admitted_on, current_date),
    nullif(btrim(coalesce(p_ward, '')), ''),
    nullif(btrim(coalesce(p_bed, '')), ''),
    v_doctor,
    v_doctor_nm,
    nullif(btrim(coalesce(p_notes, '')), ''),
    'active'
  )
  returning * into v_admission;

  return v_admission;
end;
$$;

comment on function public.save_admission(uuid, text, uuid, date, text, text, uuid, text, text) is
  'Finds or creates the episode named by (patient, hospital IPD number) and returns it, filling descriptive fields only where the stored row has none. Raises for a patient, hospital or doctor outside the caller''s pharmacy.';

-- ---------------------------------------------------------------------------
-- 6. save_patient() - find-or-create a patient, and never edit an existing one
--
--    Three behaviours worth naming, because each is a rule from the brief:
--
--      * p_patient_id given  - the operator picked a returning patient. The row is
--        checked for tenancy and returned UNCHANGED. Details typed on a bill do not
--        silently edit the master ("invoice-specific details must not silently edit
--        the master"), so the only write is a missing patient_code, which is identity
--        rather than invoice detail.
--      * nothing matches      - a new patient is registered with a generated code.
--      * the same submission twice - a retry is not a second patient. When the same
--        name and the same canonical mobile were registered by this pharmacy in the
--        last ten minutes, that row is returned instead of a duplicate. That is a
--        double-submit guard, NOT a merge: a genuinely different patient with the same
--        name and a shared family mobile is a deliberate second registration, which is
--        why the window is minutes and why the caller is shown candidates first
--        (`search_patients`) rather than being deduplicated behind its back.
--
--    Contact rule: a patient's own mobile, or a guardian's for a child or dependant
--    ("a guardian's mobile satisfies the contact requirement"). At least one of the two
--    is required; a patient with neither is refused rather than invented.
-- ---------------------------------------------------------------------------
create or replace function public.save_patient(
  p_name text,
  p_mobile text default null,
  p_patient_id uuid default null,
  p_address text default null,
  p_date_of_birth date default null,
  p_age_years int default null,
  p_age_months int default null,
  p_sex text default null,
  p_guardian_name text default null,
  p_guardian_phone text default null,
  p_notes text default null
) returns public.customers
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pharmacy   uuid := public.get_my_pharmacy_id();
  v_name       text := btrim(coalesce(p_name, ''));
  v_mobile     text := public.normalize_indian_mobile(p_mobile);
  v_guardian   text := public.normalize_indian_mobile(p_guardian_phone);
  v_sex        text := nullif(lower(btrim(coalesce(p_sex, ''))), '');
  v_patient    public.customers;
begin
  if v_pharmacy is null then
    raise exception 'no pharmacy scope for the signed-in user'
      using errcode = 'insufficient_privilege';
  end if;

  if v_name = '' then
    raise exception 'a patient needs a name'
      using errcode = 'check_violation';
  end if;

  -- A returning patient: checked, returned as-is, and given a code if it predates 7a.
  if p_patient_id is not null then
    select * into v_patient
      from public.customers c
     where c.id = p_patient_id
       and c.pharmacy_id = v_pharmacy;

    if not found then
      raise exception 'that patient is not in this pharmacy'
        using errcode = 'check_violation';
    end if;

    if v_patient.patient_code is null then
      update public.customers c
         set patient_code = public.next_patient_code()
       where c.id = v_patient.id
      returning * into v_patient;
    end if;

    return v_patient;
  end if;

  if p_mobile is not null and btrim(p_mobile) <> '' and v_mobile is null then
    raise exception 'that mobile number is not a valid Indian mobile (10 digits, starting 6-9)'
      using errcode = 'check_violation';
  end if;

  if p_guardian_phone is not null and btrim(p_guardian_phone) <> '' and v_guardian is null then
    raise exception 'that guardian mobile number is not a valid Indian mobile (10 digits, starting 6-9)'
      using errcode = 'check_violation';
  end if;

  if v_mobile is null and v_guardian is null then
    raise exception 'a patient needs a mobile number, or a guardian''s for a child or dependant'
      using errcode = 'check_violation';
  end if;

  if v_sex is not null and v_sex not in ('male', 'female', 'other') then
    raise exception 'sex must be male, female or other'
      using errcode = 'check_violation';
  end if;

  if p_date_of_birth is not null and p_date_of_birth > current_date then
    raise exception 'a date of birth cannot be in the future'
      using errcode = 'check_violation';
  end if;

  -- Double-submit guard. Scoped to this pharmacy and to the last ten minutes; see the
  -- header for why this is not a deduplicate-by-name rule.
  select * into v_patient
    from public.customers c
   where c.pharmacy_id = v_pharmacy
     and lower(btrim(c.name)) = lower(v_name)
     and coalesce(c.phone, '') = coalesce(v_mobile, v_guardian, '')
     and c.created_at > now() - interval '10 minutes'
   order by c.created_at desc
   limit 1;

  if found then
    return v_patient;
  end if;

  insert into public.customers (
    pharmacy_id, name, phone, address, patient_code,
    date_of_birth, age_years, age_months, sex,
    guardian_name, guardian_phone, notes
  ) values (
    v_pharmacy,
    v_name,
    -- The patient's own number when there is one, otherwise the guardian's, so the
    -- family is findable by the number they actually gave.
    coalesce(v_mobile, v_guardian),
    nullif(btrim(coalesce(p_address, '')), ''),
    public.next_patient_code(),
    p_date_of_birth,
    p_age_years,
    p_age_months,
    v_sex,
    nullif(btrim(coalesce(p_guardian_name, '')), ''),
    v_guardian,
    nullif(btrim(coalesce(p_notes, '')), '')
  )
  returning * into v_patient;

  return v_patient;
end;
$$;

comment on function public.save_patient(text, text, uuid, text, date, integer, integer, text, text, text, text) is
  'Registers a patient (or returns the one named by p_patient_id unchanged) with a server-generated patient code. Requires a name and a mobile or a guardian''s mobile. Scoped to the caller''s pharmacy; a repeated identical registration inside ten minutes returns the same row.';

-- ---------------------------------------------------------------------------
-- 7. search_patients() - the returning-patient lookup
--
--    Matches the three things the brief names: the canonical mobile, the patient code
--    (prefix) and the name (case-insensitive, anywhere). `normalize_indian_mobile` is
--    applied to the STORED value as well as the term, so a number saved before Phase 7a
--    in "+91 98…" form is still found - a concession to existing rows, paid for with a
--    function call per row on a table of this size rather than a bulk rewrite of data
--    the phase is not allowed to touch.
--
--    `active_admission_count` is on the result because the details step has to know
--    whether to ask which admission (a patient with two open episodes must choose).
-- ---------------------------------------------------------------------------
create or replace function public.search_patients(
  p_term text default null,
  p_limit int default 20,
  p_offset int default 0
) returns table (
  id uuid,
  name text,
  patient_code text,
  phone text,
  address text,
  date_of_birth date,
  age_years int,
  age_months int,
  sex text,
  guardian_name text,
  guardian_phone text,
  notes text,
  is_active boolean,
  active_admission_count int
)
language sql
stable
security definer
set search_path = public
as $$
  with scoped as (
    select
      c.*,
      public.normalize_indian_mobile(p_term)                          as term_mobile,
      btrim(coalesce(p_term, ''))                                     as term_text,
      (select count(*)::int
         from public.admissions a
        where a.customer_id = c.id
          and a.pharmacy_id = c.pharmacy_id
          and a.status = 'active')                                    as open_admissions
      from public.customers c
     where c.pharmacy_id = public.get_my_pharmacy_id()
  )
  select
    s.id,
    s.name,
    s.patient_code,
    s.phone,
    s.address,
    s.date_of_birth,
    s.age_years,
    s.age_months,
    s.sex,
    s.guardian_name,
    s.guardian_phone,
    s.notes,
    s.is_active,
    s.open_admissions
  from scoped s
  where s.term_text = ''
     or (s.term_mobile is not null
         and (s.phone = s.term_mobile
              or public.normalize_indian_mobile(s.phone) = s.term_mobile))
     or (s.patient_code is not null and s.patient_code ilike s.term_text || '%')
     or s.name ilike '%' || s.term_text || '%'
  order by
    case
      when s.term_mobile is not null
       and (s.phone = s.term_mobile
            or public.normalize_indian_mobile(s.phone) = s.term_mobile) then 0
      when s.patient_code ilike s.term_text || '%' then 1
      else 2
    end,
    s.name
  limit least(greatest(coalesce(p_limit, 20), 1), 50)
  offset greatest(coalesce(p_offset, 0), 0);
$$;

comment on function public.search_patients(text, integer, integer) is
  'Patient lookup by canonical mobile, patient-code prefix or case-insensitive name, tenant-scoped and paginated (max 50 rows). Read-only; an empty term lists the pharmacy''s patients.';

-- ---------------------------------------------------------------------------
-- 8. patient_admissions() - the episodes offered when a patient has several
-- ---------------------------------------------------------------------------
create or replace function public.patient_admissions(p_customer_id uuid)
returns table (
  id uuid,
  admission_no text,
  hospital_id uuid,
  hospital_name text,
  admitted_on date,
  discharged_on date,
  ward text,
  bed text,
  treating_doctor_name text,
  status text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    a.id,
    a.admission_no,
    a.hospital_id,
    h.name,
    a.admitted_on,
    a.discharged_on,
    a.ward,
    a.bed,
    a.treating_doctor_name,
    a.status,
    a.created_at
  from public.admissions a
  left join public.hospitals h on h.id = a.hospital_id
  where a.pharmacy_id = public.get_my_pharmacy_id()
    and a.customer_id = p_customer_id
  order by
    -- Open episodes first, then most recent: the one being billed is almost always an
    -- active one, and a patient's history is wanted newest-first.
    case when a.status = 'active' then 0 else 1 end,
    a.admitted_on desc,
    a.created_at desc;
$$;

comment on function public.patient_admissions(uuid) is
  'Every admission of one patient, active first. Tenant-scoped; the details step uses it to require an explicit choice when a patient has more than one open episode.';

-- ---------------------------------------------------------------------------
-- 9. Grants - the same convention as every other RPC in this tree
--
--    The code minter and the normaliser are reachable only from the definer functions
--    that gate on the tenant first, so they are revoked from every role (the same
--    treatment opening_stock_classify gets in 00031).
-- ---------------------------------------------------------------------------
do $$
begin
  execute 'grant execute on function public.save_patient(text, text, uuid, text, date, integer, integer, text, text, text, text) to authenticated';
  execute 'revoke execute on function public.save_patient(text, text, uuid, text, date, integer, integer, text, text, text, text) from anon, public';

  execute 'grant execute on function public.save_admission(uuid, text, uuid, date, text, text, uuid, text, text) to authenticated';
  execute 'revoke execute on function public.save_admission(uuid, text, uuid, date, text, text, uuid, text, text) from anon, public';

  execute 'grant execute on function public.search_patients(text, integer, integer) to authenticated';
  execute 'revoke execute on function public.search_patients(text, integer, integer) from anon, public';

  execute 'grant execute on function public.patient_admissions(uuid) to authenticated';
  execute 'revoke execute on function public.patient_admissions(uuid) from anon, public';

  execute 'revoke execute on function public.next_patient_code() from anon, authenticated, public';
  execute 'revoke execute on function public.normalize_indian_mobile(text) from anon, authenticated, public';
exception
  when undefined_object then
    -- Role or function missing in a bare (non-Supabase) cluster: nothing to grant.
    null;
end $$;
